# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L6GUEhivBxV8pytFq42tUEx6Uhexp4sl
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load Titanic dataset
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

# --- Data Cleaning ---
# Drop irrelevant columns
df = df.drop(["Name","Ticket","Cabin"], axis=1)

# Fill missing Age with median
df["Age"].fillna(df["Age"].median(), inplace=True)

# Fill missing Embarked with mode
df["Embarked"].fillna(df["Embarked"].mode()[0], inplace=True)

# Convert categorical columns
df["Sex"] = df["Sex"].map({"male":0,"female":1})
df = pd.get_dummies(df, columns=["Embarked"], drop_first=True)

# --- EDA ---
print(df.info())
print(df.describe())
print(df.corr(numeric_only=True)["Survived"].sort_values(ascending=False))

# Plot: Survival by Gender
plt.figure(figsize=(6,4))
sns.barplot(x="Sex", y="Survived", data=df)
plt.title("Survival Rate by Gender")
plt.xlabel("Gender (0=Male,1=Female)")
plt.ylabel("Survival Rate")
plt.show()

# Plot: Age distribution by survival
plt.figure(figsize=(8,5))
sns.histplot(df[df["Survived"]==1]["Age"], color="green", label="Survived", kde=False)
sns.histplot(df[df["Survived"]==0]["Age"], color="red", label="Not Survived", kde=False)
plt.title("Age Distribution by Survival")
plt.xlabel("Age")
plt.ylabel("Count")
plt.legend()
plt.show()

# Plot: Survival by Passenger Class
plt.figure(figsize=(6,4))
sns.barplot(x="Pclass", y="Survived", data=df)
plt.title("Survival Rate by Passenger Class")
plt.xlabel("Passenger Class")
plt.ylabel("Survival Rate")
plt.show()